# Generated by Django 4.2.8 on 2024-05-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="note",
            field=models.CharField(blank=True, null=True),
        ),
    ]
