# Generated by Django 4.2.8 on 2024-05-07 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contacts", "0003_alter_contact_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("user", "email")},
        ),
    ]
