# Generated by Django 4.2.8 on 2024-05-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together=set(),
        ),
    ]
