# Generated by Django 4.2.8 on 2024-05-07 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_alter_contact_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="time_create",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
