# Generated by Django 4.2.8 on 2024-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("short_description", models.TextField()),
                ("news_link", models.URLField()),
                ("photo_link", models.URLField()),
            ],
        ),
    ]
