# Generated by Django 5.0.4 on 2024-05-07 10:14

import s3_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_storage', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=s3_storage.models.upload_to_s3),
        ),
    ]
